<?php
/**
 * @file
 * commerce_discount_firsttime.module
 */

/**
 * Conditions to implement commerce_order_first_time rule.
 */
function commerce_discount_firsttime_customer_build(EntityDrupalWrapper $wrapper) {
  $uid = $wrapper->uid->value();

  // If user is anonymous validate discount.
  if ($uid === '0') {
    return TRUE;
  }
  else {
    // Get given total order amount.
    $sql = 'SELECT COUNT(uid) FROM {commerce_order} WHERE uid = :uid';
    $total_orders = db_query($sql, array(':uid' => $uid))->fetchField();

    // If user has 1 or fewer orders.
    if ($total_orders <= 1) {
      return TRUE;
    }
  }

  return FALSE;
}
